<?php
return array (
  'title' => '分类信息',
  'style' => '1',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '中国',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3361,3366,3367,3368,3369,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388,3389,3390,3391,3392,3393,3394,3395,3396,3397,3398,3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '0',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '山东',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3366',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '江苏',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3367',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '安徽',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3368',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '浙江',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3369',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '福建',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3370',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '上海',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '广东',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '广西',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '海南',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '湖北',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3375',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3376 => 
    array (
      'linkageid' => '3376',
      'name' => '湖南',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3376',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3377 => 
    array (
      'linkageid' => '3377',
      'name' => '河南',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3377',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3378 => 
    array (
      'linkageid' => '3378',
      'name' => '江西',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3378',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3379 => 
    array (
      'linkageid' => '3379',
      'name' => '北京',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3379',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '天津',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '河北',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '山西',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '内蒙古',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '宁夏',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '新疆',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '青海',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '陕西',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '甘肃',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '四川',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '云南',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '贵州',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '西藏',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '重庆',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '辽宁',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '吉林',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '黑龙江',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '台湾',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '香港',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '澳门',
      'style' => '',
      'parentid' => '3361',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => '',
      'siteid' => '0',
    ),
  ),
);
?>