<?php
return array (
  12 => 
  array (
    'catid' => '12',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '12',
    'catname' => '包机飞行',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=12',
    'items' => '1',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '12',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'baojifeixing',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  13 => 
  array (
    'catid' => '13',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '13',
    'catname' => '飞行器静态租赁',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=13',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '13',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'feixingqijingtaizulin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  14 => 
  array (
    'catid' => '14',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '14',
    'catname' => '飞行器托管',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=14',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '14',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'feixingqituoguan',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  15 => 
  array (
    'catid' => '15',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '15',
    'catname' => '航油',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=15',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '15',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'hangyou',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  16 => 
  array (
    'catid' => '16',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '16',
    'catname' => '航材',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=16',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '16',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'hangcai',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  17 => 
  array (
    'catid' => '17',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '15',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '17',
    'catname' => '飞行执照',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=lists&catid=17',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '17',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'feixingzhizhao',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>