<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => '飞行',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=list_company&catid=9',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'feixing',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  10 => 
  array (
    'catid' => '10',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '10',
    'catname' => '无人机',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=list_company&catid=10',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '10',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'wurenji',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  11 => 
  array (
    'catid' => '11',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '11',
    'catname' => '客机',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://tonghangyun.com/index.php?m=yp&c=index&a=list_company&catid=11',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '11',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'keji',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>