<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  2 => 
  array (
    'modelid' => '2',
    'siteid' => '1',
    'name' => '下载模型',
    'description' => '',
    'tablename' => 'download',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_download',
    'list_template' => 'list_download',
    'show_template' => 'show_download',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  3 => 
  array (
    'modelid' => '3',
    'siteid' => '1',
    'name' => '图片模型',
    'description' => '',
    'tablename' => 'picture',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list_picture',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  11 => 
  array (
    'modelid' => '11',
    'siteid' => '1',
    'name' => '视频模型',
    'description' => '',
    'tablename' => 'video',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_video',
    'list_template' => 'list_video',
    'show_template' => 'show_video',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '包机飞行',
    'description' => '',
    'tablename' => 'house_new',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  14 => 
  array (
    'modelid' => '14',
    'siteid' => '1',
    'name' => '飞行器租赁',
    'description' => '飞行器租赁',
    'tablename' => 'zulin',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  16 => 
  array (
    'modelid' => '16',
    'siteid' => '1',
    'name' => '飞行器托管',
    'description' => '飞行器托管',
    'tablename' => 'tuoguan',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  17 => 
  array (
    'modelid' => '17',
    'siteid' => '1',
    'name' => '航油',
    'description' => '航油',
    'tablename' => 'hangyou',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  18 => 
  array (
    'modelid' => '18',
    'siteid' => '1',
    'name' => '航材',
    'description' => '航材',
    'tablename' => 'hangcai',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  19 => 
  array (
    'modelid' => '19',
    'siteid' => '1',
    'name' => '飞行执照',
    'description' => '飞行执照',
    'tablename' => 'zhizhao',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  21 => 
  array (
    'modelid' => '21',
    'siteid' => '1',
    'name' => '其他',
    'description' => '其他',
    'tablename' => 'other',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_house',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  22 => 
  array (
    'modelid' => '22',
    'siteid' => '1',
    'name' => '推荐位',
    'description' => '推荐位',
    'tablename' => 'tuijian',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  25 => 
  array (
    'modelid' => '25',
    'siteid' => '1',
    'name' => 'app下载',
    'description' => '',
    'tablename' => 'download',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_picture',
    'list_template' => 'list',
    'show_template' => 'show_picture',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  26 => 
  array (
    'modelid' => '26',
    'siteid' => '1',
    'name' => '检索页',
    'description' => '',
    'tablename' => 'jiansuo',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category_info',
    'list_template' => 'list_jiansuo',
    'show_template' => 'show_house',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>